language: c
sudo: required

install:
  - # Add PPA with newer version of sdcc backported to precise.
  - sudo add-apt-repository -y ppa:mithro/sdcc-precise
  - sudo apt-get update
  - # Need libusb-dev for fx2loader and other tools
  - sudo apt-get install -y libusb-1.0-0-dev
  - # Install sdcc
  - sudo apt-get install --force-yes -y sdcc
  - sdcc --version

script:
  - make
